# This table stores derived insight, not raw truth.
"""
- Generated by LLM or rules
- Human-readable
- Optional
- Disposable

Think of it as:
“Given everything we know, what should a human do?"
"""

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, Text, func
from db.base import Base


class Recommendation(Base):
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)

    query_id = Column(
        Integer, ForeignKey("queries.id", ondelete="CASCADE"), nullable=False
    )

    generated_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    severity = Column(Text, nullable=False)  # e.g., 'low', 'medium', 'high'

    summary = Column(Text, nullable=False)  # Short human-readable advice
    details = Column(Text, nullable=True)  # Longer explanation or fix

    confidence_score = Column(
        Float, nullable=True
    )  # How sure the system is about this recommendation


# Conceptual SQL schema for the recommendations table
"""
CREATE TABLE recommendations (
    id SERIAL PRIMARY KEY,
    query_id INTEGER NOT NULL REFERENCES queries(id) ON DELETE CASCADE,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    severity TEXT NOT NULL,
    summary TEXT NOT NULL,
    details TEXT,
    confidence_score FLOAT
);
"""

# Documentation of the recommendations table
"""
| Column             | Meaning                        |
| ------------------ | ------------------------------ |
| `query_id`         | Which query this advice is for |
| `generated_at`     | When the advice was generated  |
| `severity`         | How important the issue is     |
| `summary`          | Short human-readable advice    |
| `details`          | Longer explanation or fix      |
| `confidence_score` | How sure the system is         |
"""

# Example data in the recommendations table
"""
queries
-------
id = 1 → SELECT * FROM users WHERE id = ?
id = 2 → SELECT * FROM orders WHERE user_id = ?

recommendations
-------
| id | query_id | generated_at (UTC)     | severity | summary                         | details                                                                        | confidence_score |
| -- | -------- | ---------------------- | -------- | ------------------------------- | ------------------------------------------------------------------------------ | ---------------- |
| 1  | 1        | 2026-01-02 10:05:00+00 | low      | Query is healthy and uses index | Index scan detected on primary key; no action required                         | 0.92             |
| 2  | 2        | 2026-01-02 15:10:30+00 | high     | Sequential scan on large table  | Query performs full table scan on `orders`; consider adding index on `user_id` | 0.88             |
| 3  | 2        | 2026-01-02 18:45:00+00 | medium   | Execution time increased        | Execution time increased by 40% compared to previous analysis                  | 0.76             |

"""
